### ISSUE TITLE
Repo URL incorrect

### ISSUE THREAD

**Issue by lied** [kawasakitoshiya/ansible-td-agent#9]
This line 
`apt_repository: repo='deb http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib' state=present`
 has to expanded to
`apt_repository: repo='deb [arch=amd64] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib' state=present`

work correctly. I have only tested in on Ubuntu Trusty (amd64) but I guess, that this is applies also to the other Ubuntu versions.

**Comment by yacchin1205** [comment]
I encountered the same problem.
In my case, like https://github.com/treasure-data/chef-td-agent/issues/53#issuecomment-108149019, my machine(Ubuntu 14.04) has i386 as foreign-architecture. After I run this role on my machine, an error `Failed to fetch` occurs. It may be caused by td-agent provides no i386 binaries for Ubuntu 14.04.
So I want some way to set an arch to the Repo URL.

I guess that it is better to use variable `td_agent_architecture` (https://github.com/kawasakitoshiya/ansible-td-agent#role-variables).
I'm testing tasks like below...

```
apt_repository: repo='deb [arch={{ td_agent_architecture }}] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib' state=present
```
